/**
 * Database definition — creates the DB instance and exports it.
 * DB() auto-registers on the app. Entities register on this db instance.
 *
 * Type generated by velogen: npm run velogen -- examples/full-demo
 */
import { DB } from '@velocity/framework';
import type { TypedDb } from './generated/velocity-types';

export const db = DB({
  type: 'sqlite',
  database: ':memory:',
  filename: ':memory:'
}) as TypedDb;
