/**
 * SQLite database — users.
 *
 * Type generated by velogen: npm run velogen -- examples/full-demo
 */
import { DB } from '@velocity/framework';
import type { TypedDb } from './velo/velotypes';
import { envelocity } from './velo/envelocity';

export const db = DB({
  type: 'sqlite',
  database: envelocity.db.databaseOrThrow,
  filename: envelocity.db.filenameOrThrow,
}) as TypedDb;
