/**
 * PostgreSQL database — posts, job_records.
 *
 * Configure in .env:
 *   PG__HOST, PG__PORT, PG__DATABASE, PG__USER, PG__PASSWORD
 *   PG__POOL__MIN, PG__POOL__MAX
 *
 * Type generated by velogen: npm run velogen -- examples/full-demo
 */
import { DB } from '@velocity/framework';
import type { TypedPgDb } from './velo/velocity-types';
import { envelocity } from './velo/envelocity';

export const pgDb = DB('pgdb', {
  type: 'postgresql',
  database: envelocity.pg.databaseOrThrow,
  host: envelocity.pg.hostOrThrow,
  port: parseInt(envelocity.pg.portOrThrow),
  username: envelocity.pg.userOrThrow,
  password: envelocity.pg.passwordOrThrow,
  pool: {
    min: parseInt(envelocity.pg.pool.minOrThrow),
    max: parseInt(envelocity.pg.pool.maxOrThrow),
  },
}) as TypedPgDb;
