// Auto-generated by envgen — do not edit manually
// Re-run: npm run envgen -- examples/full-demo

import { createEnvelocity } from '@velocity/framework';
import * as path from 'path';

const ENV_KEYS = [
  'APP_DEBUG',
  'APP_NAME',
  'AUTH__JWT_SECRET',
  'AUTH__TOKEN_EXPIRY',
  'DB__DATABASE',
  'DB__FILENAME',
  'DB__TYPE',
  'PG__DATABASE',
  'PG__HOST',
  'PG__PASSWORD',
  'PG__POOL__MAX',
  'PG__POOL__MIN',
  'PG__PORT',
  'PG__USER',
  'SERVER__HOST',
  'SERVER__PORT',
];

export interface EnvelocityConfig {
  readonly appDebug: string | undefined;
  readonly appDebugOrThrow: string;
  readonly appName: string | undefined;
  readonly appNameOrThrow: string;
  readonly auth: {
    readonly jwtSecret: string | undefined;
    readonly jwtSecretOrThrow: string;
    readonly tokenExpiry: string | undefined;
    readonly tokenExpiryOrThrow: string;
  };
  readonly db: {
    readonly database: string | undefined;
    readonly databaseOrThrow: string;
    readonly filename: string | undefined;
    readonly filenameOrThrow: string;
    readonly type: string | undefined;
    readonly typeOrThrow: string;
  };
  readonly pg: {
    readonly database: string | undefined;
    readonly databaseOrThrow: string;
    readonly host: string | undefined;
    readonly hostOrThrow: string;
    readonly password: string | undefined;
    readonly passwordOrThrow: string;
    readonly pool: {
      readonly max: string | undefined;
      readonly maxOrThrow: string;
      readonly min: string | undefined;
      readonly minOrThrow: string;
    };
    readonly port: string | undefined;
    readonly portOrThrow: string;
    readonly user: string | undefined;
    readonly userOrThrow: string;
  };
  readonly server: {
    readonly host: string | undefined;
    readonly hostOrThrow: string;
    readonly port: string | undefined;
    readonly portOrThrow: string;
  };
}

export const envelocity: EnvelocityConfig = createEnvelocity({
  envFile: path.resolve(__dirname, '../.env'),
  keys: ENV_KEYS,
});
