// Auto-generated by velogen-client — do not edit manually
// Re-run: velogen c examples/full-demo

const DEFAULT_BASE = 'http://localhost:5000';

type RequestOptions = { headers?: Record<string, string>; signal?: AbortSignal };
interface WsResponse { ok: boolean; cmd: string; data: unknown; error: string | null }

function _createFetch(base: string) {
  return async (method: string, path: string, body?: unknown, opts?: RequestOptions) => {
    const headers: Record<string, string> = { ...opts?.headers };
    const init: RequestInit = { method, headers, signal: opts?.signal };
    if (body !== undefined) {
      headers['Content-Type'] = 'application/json';
      init.body = JSON.stringify(body);
    }
    const res = await fetch(base + path, init);
    if (res.status === 204) return undefined;
    const text = await res.text();
    try { return JSON.parse(text); } catch { return text; }
  };
}

function _createWs(wsBase: string, path: string) {
  const sock = new globalThis.WebSocket(wsBase + path);
  const pending = new Map<string, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();
  sock.onmessage = (e) => {
    try {
      const msg: WsResponse = JSON.parse(e.data);
      const p = pending.get(msg.cmd);
      if (p) { pending.delete(msg.cmd); msg.ok ? p.resolve(msg.data) : p.reject(new Error(msg.error || 'Unknown')); }
    } catch {}
  };
  return {
    raw: sock,
    send(cmd: string, data?: unknown): Promise<unknown> {
      return new Promise((resolve, reject) => {
        pending.set(cmd, { resolve, reject });
        sock.send(JSON.stringify({ cmd, data }));
      });
    },
    close() { sock.close(); },
  };
}

function _buildVelient(base: string) {
  const _fetch = _createFetch(base);
  const wsBase = base.replace(/^http/, 'ws');
  return {
    health: {
      health: (opts?: RequestOptions) =>
        _fetch('GET', '/health/', undefined, opts),
    },
    job: {
      list: (opts?: RequestOptions) =>
        _fetch('GET', '/jobs/', undefined, opts),
      results: (opts?: RequestOptions) =>
        _fetch('GET', '/jobs/results', undefined, opts),
      getById: (id: string, opts?: RequestOptions) =>
        _fetch('GET', `/jobs/${id}`, undefined, opts),
    },
    post: {
      list: (opts?: RequestOptions) =>
        _fetch('GET', '/posts/', undefined, opts),
      getById: (id: string, opts?: RequestOptions) =>
        _fetch('GET', `/posts/${id}`, undefined, opts),
      remove: (id: string, opts?: RequestOptions) =>
        _fetch('DELETE', `/posts/${id}`, undefined, opts),
    },
    user: {
      list: (opts?: RequestOptions) =>
        _fetch('GET', '/users/', undefined, opts),
      getById: (id: string, opts?: RequestOptions) =>
        _fetch('GET', `/users/${id}`, undefined, opts),
      remove: (id: string, opts?: RequestOptions) =>
        _fetch('DELETE', `/users/${id}`, undefined, opts),
    },
    fn: {
      findUser: (...args: unknown[]) =>
        _fetch('GET', `/.${encodeURIComponent('findUser')}(${args.map(a => typeof a === 'string' ? `"${a}"` : String(a)).join(',')})`),
      countUsers: (...args: unknown[]) =>
        _fetch('GET', `/.${encodeURIComponent('countUsers')}(${args.map(a => typeof a === 'string' ? `"${a}"` : String(a)).join(',')})`),
      greet: (...args: unknown[]) =>
        _fetch('GET', `/.${encodeURIComponent('greet')}(${args.map(a => typeof a === 'string' ? `"${a}"` : String(a)).join(',')})`),
    },
    ws: {
      chat: {
        connect() {
          const conn = _createWs(wsBase, '/ws/chat');
          return {
            ...conn,
            ping: (data?: unknown) => conn.send('ping', data),
            time: (data?: unknown) => conn.send('time', data),
            broadcast: (data?: unknown) => conn.send('broadcast', data),
            echo: (data?: unknown) => conn.send('echo', data),
          };
        },
      },
      echo: {
        connect() {
          const conn = _createWs(wsBase, '/ws/echo');
          return {
            ...conn,
          };
        },
      },
    },
  };
}

// Default client (base: http://localhost:5000)
const _default = _buildVelient(DEFAULT_BASE);

export const health = _default.health;
export const job = _default.job;
export const post = _default.post;
export const user = _default.user;
export const fn = _default.fn;
export const ws = _default.ws;

/** Create a client with a custom base URL. */
export function Velient(baseUrl: string = DEFAULT_BASE) {
  return _buildVelient(baseUrl);
}
