// Auto-generated by velogen-client — do not edit manually
// Re-run: npm run client -- examples/full-demo

const BASE = 'http://localhost:5000';

type RequestOptions = { headers?: Record<string, string>; signal?: AbortSignal };

async function _fetch(method: string, path: string, body?: any, opts?: RequestOptions) {
  const headers: Record<string, string> = { ...opts?.headers };
  const init: RequestInit = { method, headers, signal: opts?.signal };
  if (body !== undefined) {
    headers['Content-Type'] = 'application/json';
    init.body = JSON.stringify(body);
  }
  const res = await fetch(BASE + path, init);
  if (res.status === 204) return undefined;
  const text = await res.text();
  try { return JSON.parse(text); } catch { return text; }
}

export const health = {
  health: (opts?: RequestOptions) =>
    _fetch('GET', '/health/', undefined, opts),
};

export const job = {
  list: (opts?: RequestOptions) =>
    _fetch('GET', '/jobs/', undefined, opts),
  results: (opts?: RequestOptions) =>
    _fetch('GET', '/jobs/results', undefined, opts),
  getById: (id: string, opts?: RequestOptions) =>
    _fetch('GET', `/jobs/${id}`, undefined, opts),
};

export const post = {
  list: (opts?: RequestOptions) =>
    _fetch('GET', '/posts/', undefined, opts),
  getById: (id: string, opts?: RequestOptions) =>
    _fetch('GET', `/posts/${id}`, undefined, opts),
  remove: (id: string, opts?: RequestOptions) =>
    _fetch('DELETE', `/posts/${id}`, undefined, opts),
};

export const user = {
  list: (opts?: RequestOptions) =>
    _fetch('GET', '/users/', undefined, opts),
  getById: (id: string, opts?: RequestOptions) =>
    _fetch('GET', `/users/${id}`, undefined, opts),
  remove: (id: string, opts?: RequestOptions) =>
    _fetch('DELETE', `/users/${id}`, undefined, opts),
};

