// Auto-generated by velogen-client — do not edit manually
// Re-run: velogen c examples/full-demo

const BASE = 'http://localhost:5000';
const WS_BASE = BASE.replace(/^http/, 'ws');

type RequestOptions = { headers?: Record<string, string>; signal?: AbortSignal };

async function _fetch(method: string, path: string, body?: unknown, opts?: RequestOptions) {
  const headers: Record<string, string> = { ...opts?.headers };
  const init: RequestInit = { method, headers, signal: opts?.signal };
  if (body !== undefined) {
    headers['Content-Type'] = 'application/json';
    init.body = JSON.stringify(body);
  }
  const res = await fetch(BASE + path, init);
  if (res.status === 204) return undefined;
  const text = await res.text();
  try { return JSON.parse(text); } catch { return text; }
}

export const health = {
  health: (opts?: RequestOptions) =>
    _fetch('GET', '/health/', undefined, opts),
};

export const job = {
  list: (opts?: RequestOptions) =>
    _fetch('GET', '/jobs/', undefined, opts),
  results: (opts?: RequestOptions) =>
    _fetch('GET', '/jobs/results', undefined, opts),
  getById: (id: string, opts?: RequestOptions) =>
    _fetch('GET', `/jobs/${id}`, undefined, opts),
};

export const post = {
  list: (opts?: RequestOptions) =>
    _fetch('GET', '/posts/', undefined, opts),
  getById: (id: string, opts?: RequestOptions) =>
    _fetch('GET', `/posts/${id}`, undefined, opts),
  remove: (id: string, opts?: RequestOptions) =>
    _fetch('DELETE', `/posts/${id}`, undefined, opts),
};

export const user = {
  list: (opts?: RequestOptions) =>
    _fetch('GET', '/users/', undefined, opts),
  getById: (id: string, opts?: RequestOptions) =>
    _fetch('GET', `/users/${id}`, undefined, opts),
  remove: (id: string, opts?: RequestOptions) =>
    _fetch('DELETE', `/users/${id}`, undefined, opts),
};

// ─── HTTP Function Calls (@Fn) ───

export const fn = {
  findUser: (...args: unknown[]) =>
    _fetch('GET', `/.${encodeURIComponent('findUser')}(${args.map(a => typeof a === 'string' ? `"${a}"` : String(a)).join(',')})`),
  countUsers: (...args: unknown[]) =>
    _fetch('GET', `/.${encodeURIComponent('countUsers')}(${args.map(a => typeof a === 'string' ? `"${a}"` : String(a)).join(',')})`),
  greet: (...args: unknown[]) =>
    _fetch('GET', `/.${encodeURIComponent('greet')}(${args.map(a => typeof a === 'string' ? `"${a}"` : String(a)).join(',')})`),
};

// ─── WebSocket ───

interface WsResponse { ok: boolean; cmd: string; data: unknown; error: string | null }

function _ws(path: string) {
  const ws = new globalThis.WebSocket(WS_BASE + path);
  const pending = new Map<string, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();
  let idCounter = 0;
  ws.onmessage = (e) => {
    try {
      const msg: WsResponse = JSON.parse(e.data);
      const p = pending.get(msg.cmd);
      if (p) { pending.delete(msg.cmd); msg.ok ? p.resolve(msg.data) : p.reject(new Error(msg.error || 'Unknown error')); }
    } catch {}
  };
  return {
    raw: ws,
    send(cmd: string, data?: unknown): Promise<unknown> {
      return new Promise((resolve, reject) => {
        pending.set(cmd, { resolve, reject });
        ws.send(JSON.stringify({ cmd, data }));
      });
    },
    close() { ws.close(); },
  };
}

export const ws = {
  chat: {
    connect: () => {
      const conn = _ws('/ws/chat');
      return {
        ...conn,
        ping: (data?: unknown) => conn.send('ping', data),
        time: (data?: unknown) => conn.send('time', data),
        broadcast: (data?: unknown) => conn.send('broadcast', data),
        echo: (data?: unknown) => conn.send('echo', data),
      };
    },
  },
  echo: {
    connect: () => {
      const conn = _ws('/ws/echo');
      return {
        ...conn,
      };
    },
  },
};
