// Auto-generated by velogen — do not edit manually
// Re-run: npm run velogen -- examples/full-demo

import type { EntityAccessor, Database } from '@velocity/framework';
import type { User } from '../src/entities/user.entity';
import type { Post } from '../src/entities/post.entity';

/** Typed database interface for `db` */
export interface TypedDb extends Database {
  readonly User: EntityAccessor<User>;
  readonly Post: EntityAccessor<Post>;
}
