#!/usr/bin/env node
/**
 * envgen — Envelocity Type Generator
 *
 * Reads a .env file and generates a typed, read-only envelocity config module.
 *
 * Usage:
 *   npm run envgen -- examples/full-demo
 *
 * Naming rules:
 *   Single _   → camelCase:     ENV_FIELD          → envField
 *   Double __  → nesting:       ENV_A__B           → envA.b
 *   Triple ___ → leading _:     ENV_A___B          → envA._b
 *
 * Conflict resolution:
 *   If ENV_A__B=x AND ENV_A__B__C=y, then b = { default: x, c: y }
 *
 * Output:
 *   <project>/generated/envelocity.ts   — typed config with OrThrow getters
 */

const fs = require('fs');
const path = require('path');

// ─── Arg parsing ───

const targetDir = process.argv[2];
if (!targetDir) {
  console.error('Usage: envgen <project-directory>');
  console.error('  e.g.: npm run envgen -- examples/full-demo');
  process.exit(1);
}

const projectDir = path.resolve(targetDir);
const envFile = path.join(projectDir, '.env');

if (!fs.existsSync(envFile)) {
  console.error(`No .env file found in ${projectDir}`);
  process.exit(1);
}

// ─── .env parser ───

function parseEnvFile(filePath) {
  const result = {};
  const content = fs.readFileSync(filePath, 'utf-8');

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const cleaned = trimmed.startsWith('export ') ? trimmed.slice(7) : trimmed;
    const eqIndex = cleaned.indexOf('=');
    if (eqIndex === -1) continue;

    const key = cleaned.slice(0, eqIndex).trim();
    let value = cleaned.slice(eqIndex + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }

  return result;
}

// ─── camelCase converter ───

function toCamelCase(segment) {
  let leading = '';
  let rest = segment;
  while (rest.startsWith('_')) {
    leading += '_';
    rest = rest.slice(1);
  }
  if (!rest) return leading;

  const parts = rest.split('_').filter(Boolean);
  const camel = parts.map((p, i) => {
    const lower = p.toLowerCase();
    return i === 0 ? lower : lower[0].toUpperCase() + lower.slice(1);
  }).join('');

  return leading + camel;
}

// ─── Tree builder ───

function buildTree(flat) {
  const tree = {};

  const sortedKeys = Object.keys(flat).sort((a, b) =>
    a.split('__').length - b.split('__').length
  );

  for (const key of sortedKeys) {
    const value = flat[key];
    const segments = key.split('__').filter(Boolean);
    const pathParts = segments.map(toCamelCase);

    let current = tree;
    for (let i = 0; i < pathParts.length - 1; i++) {
      const seg = pathParts[i];
      if (typeof current[seg] === 'string') {
        current[seg] = { default: current[seg] };
      }
      if (!current[seg] || typeof current[seg] !== 'object') {
        current[seg] = {};
      }
      current = current[seg];
    }

    const leaf = pathParts[pathParts.length - 1];
    if (typeof current[leaf] === 'object' && current[leaf] !== null) {
      current[leaf].default = value;
    } else {
      current[leaf] = value;
    }
  }

  return tree;
}

// ─── Type generator ───

function generateType(tree, indent) {
  let output = '';
  const entries = Object.entries(tree).sort(([a], [b]) => a.localeCompare(b));

  for (const [key, value] of entries) {
    if (typeof value === 'object' && value !== null) {
      output += `${indent}readonly ${key}: {\n`;
      output += generateType(value, indent + '  ');
      output += `${indent}};\n`;
    } else {
      output += `${indent}readonly ${key}: string | undefined;\n`;
      output += `${indent}readonly ${key}OrThrow: string;\n`;
    }
  }

  return output;
}

// ─── Main ───

const envVars = parseEnvFile(envFile);
const keys = Object.keys(envVars);

if (keys.length === 0) {
  console.log('No environment variables found in .env');
  process.exit(0);
}

const tree = buildTree(envVars);

// Generate output
const outputDir = path.join(projectDir, 'generated');
fs.mkdirSync(outputDir, { recursive: true });

const outputFile = path.join(outputDir, 'envelocity.ts');
const relEnvPath = path.relative(outputDir, envFile).replace(/\\/g, '/');
const relProjectDir = path.relative(process.cwd(), projectDir);

let output = `// Auto-generated by envgen — do not edit manually\n`;
output += `// Re-run: npm run envgen -- ${relProjectDir}\n\n`;
output += `import { createEnvelocity } from '@velocity/framework';\n`;
output += `import * as path from 'path';\n\n`;

// Keys array
output += `const ENV_KEYS = [\n`;
for (const key of keys.sort()) {
  output += `  '${key}',\n`;
}
output += `];\n\n`;

// Type interface
output += `export interface EnvelocityConfig {\n`;
output += generateType(tree, '  ');
output += `}\n\n`;

// Runtime export
output += `export const envelocity: EnvelocityConfig = createEnvelocity({\n`;
output += `  envFile: path.resolve(__dirname, '${relEnvPath}'),\n`;
output += `  keys: ENV_KEYS,\n`;
output += `});\n`;

fs.writeFileSync(outputFile, output);

console.log(`envgen: generated ${path.relative(process.cwd(), outputFile)}`);
console.log(`  ${keys.length} env vars → ${Object.keys(tree).length} top-level keys`);

// Print tree summary
function printTree(obj, prefix) {
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'object' && value !== null) {
      console.log(`  ${prefix}${key}:`);
      printTree(value, prefix + '  ');
    } else {
      console.log(`  ${prefix}${key} = "${value}"`);
    }
  }
}
printTree(tree, '  ');
