#!/usr/bin/env node
/**
 * velogen — Velocity Type Generator
 *
 * Generates TypeScript types for Database instances based on registered entities.
 * Eliminates `as any` casts when accessing db.EntityName.
 *
 * Usage:
 *   npx velogen <project-dir>
 *   npm run velogen -- examples/full-demo
 *
 * What it does:
 *   1. Scans for *.entity.ts files to find @Entity classes
 *   2. Finds db.register(Entity) calls to map entities → DB variables
 *   3. Generates a velocity-types.d.ts with typed DB interfaces
 *
 * After running, update your db.ts to use the generated type:
 *   import type { TypedDb } from './velo/velocity-types';
 *   export const db = DB({ ... }) as TypedDb;
 */

const fs = require('fs');
const path = require('path');

// ─── Arg parsing ───
const targetDir = process.argv[2];
if (!targetDir) {
  console.error('Usage: velogen <project-directory>');
  console.error('  e.g.: npm run velogen -- examples/full-demo');
  process.exit(1);
}

const projectDir = path.resolve(targetDir);
if (!fs.existsSync(projectDir)) {
  console.error(`Directory not found: ${projectDir}`);
  process.exit(1);
}

// ─── Scan helpers ───

function findFiles(dir, pattern) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== 'velo') {
      results.push(...findFiles(fullPath, pattern));
    } else if (entry.isFile() && pattern.test(entry.name)) {
      results.push(fullPath);
    }
  }
  return results;
}

// ─── Parse entity files ───

function parseEntityFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');

  // Must have @Entity decorator
  if (!/@Entity\s*\(/.test(content)) return null;

  // Extract class name
  const classMatch = content.match(/(?:export\s+)?class\s+(\w+)/);
  if (!classMatch) return null;
  const className = classMatch[1];

  // Extract db variable from: someVar.register(ClassName)
  const registerMatch = content.match(/(\w+)\.register\s*\(\s*(\w+)\s*\)/);
  if (!registerMatch || registerMatch[2] !== className) return null;

  return { className, dbVar: registerMatch[1], filePath };
}

// ─── Main ───

const entityFiles = findFiles(projectDir, /\.entity\.ts$/);
if (entityFiles.length === 0) {
  console.log('No *.entity.ts files found.');
  process.exit(0);
}

const entities = entityFiles.map(parseEntityFile).filter(Boolean);
if (entities.length === 0) {
  console.log('No entities with db.register() found.');
  process.exit(0);
}

// Group entities by DB variable
const entityGroups = new Map();
for (const entity of entities) {
  if (!entityGroups.has(entity.dbVar)) {
    entityGroups.set(entity.dbVar, []);
  }
  entityGroups.get(entity.dbVar).push(entity);
}

// ─── Generate output ───

const outputDir = path.join(projectDir, 'velo');
fs.mkdirSync(outputDir, { recursive: true });

const outputFile = path.join(outputDir, 'velocity-types.d.ts');

let output = `// Auto-generated by velogen — do not edit manually\n`;
output += `// Re-run: npm run velogen -- ${path.relative(process.cwd(), projectDir)}\n\n`;
output += `import type { EntityAccessor, Database } from '@velocity/framework';\n`;

// Import each entity class
for (const entity of entities) {
  const relPath = path.relative(outputDir, entity.filePath).replace(/\.ts$/, '');
  const importPath = relPath.startsWith('.') ? relPath : './' + relPath;
  output += `import type { ${entity.className} } from '${importPath}';\n`;
}

output += `\n`;

// Generate typed interface for each DB variable
for (const [dbVar, dbEntities] of entityGroups) {
  const interfaceName = `Typed${dbVar.charAt(0).toUpperCase() + dbVar.slice(1)}`;

  output += `/** Typed database interface for \`${dbVar}\` */\n`;
  output += `export interface ${interfaceName} extends Database {\n`;
  for (const entity of dbEntities) {
    output += `  readonly ${entity.className}: EntityAccessor<${entity.className}>;\n`;
  }
  output += `}\n`;
}

fs.writeFileSync(outputFile, output);

console.log(`velogen: generated ${path.relative(process.cwd(), outputFile)}`);
console.log(`  ${entities.length} entities across ${entityGroups.size} database(s)`);
for (const [dbVar, dbEntities] of entityGroups) {
  const interfaceName = `Typed${dbVar.charAt(0).toUpperCase() + dbVar.slice(1)}`;
  console.log(`  ${dbVar} -> ${interfaceName}: ${dbEntities.map(e => e.className).join(', ')}`);
}
