#!/usr/bin/env node
/**
 * velogen-openapi — Velocity OpenAPI 3.1 Generator
 *
 * Scans controller files for @Controller, @Get/@Post/etc. decorators and
 * generates an openapi.json spec from the route metadata.
 *
 * Usage:
 *   node scripts/velogen-openapi.js <project-dir>
 *   npm run openapi -- examples/full-demo
 */

const fs = require('fs');
const path = require('path');

const targetDir = process.argv[2];
if (!targetDir) {
  console.error('Usage: velogen-openapi <project-directory>');
  process.exit(1);
}

const projectDir = path.resolve(targetDir);
if (!fs.existsSync(projectDir)) {
  console.error(`Directory not found: ${projectDir}`);
  process.exit(1);
}

// ─── Helpers ───

function findFiles(dir, pattern) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== 'velo' && entry.name !== 'dist') {
      results.push(...findFiles(fullPath, pattern));
    } else if (entry.isFile() && pattern.test(entry.name)) {
      results.push(fullPath);
    }
  }
  return results;
}

// ─── Parse controller files ───

const HTTP_METHODS = ['Get', 'Post', 'Put', 'Delete', 'Patch'];
const methodRegex = new RegExp(
  `@(${HTTP_METHODS.join('|')})\\s*\\(\\s*['"\`]([^'"\`]*)['"\`]\\s*\\)`,
  'g'
);
const controllerRegex = /@Controller\s*\(\s*['"`]([^'"`]*)['"`]\s*\)/;
const validateRegex = /@Validate\s*\(/;
const useGuardRegex = /@UseGuard\s*\(/;
const uploadRegex = /@Upload\s*\(/;

function parseControllerFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const ctrlMatch = content.match(controllerRegex);
  if (!ctrlMatch) return null;

  const basePath = ctrlMatch[1];
  const className = (content.match(/(?:export\s+)?class\s+(\w+)/) || [])[1] || 'Unknown';
  const routes = [];

  // Split content into lines for context
  const lines = content.split('\n');

  let match;
  methodRegex.lastIndex = 0;
  while ((match = methodRegex.exec(content)) !== null) {
    const httpMethod = match[1].toLowerCase();
    const routePath = match[2];
    const decoratorPos = match.index;

    // Find the method name: skip past the decorator and any following decorators
    const afterDecorator = content.slice(decoratorPos + match[0].length);
    let methodName = 'unknown';
    for (const line of afterDecorator.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('@') || trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
      const m = trimmed.match(/^(?:async\s+)?(\w+)\s*\(/);
      if (m) { methodName = m[1]; break; }
    }

    // Check for path parameters
    const params = [];
    const paramMatches = routePath.matchAll(/:(\w+)/g);
    for (const pm of paramMatches) {
      params.push(pm[1]);
    }

    // Check if route has @Validate (indicates request body schema)
    const lineNum = content.slice(0, decoratorPos).split('\n').length;
    const contextStart = Math.max(0, lineNum - 5);
    const contextEnd = Math.min(lines.length, lineNum + 5);
    const context = lines.slice(contextStart, contextEnd).join('\n');
    const hasValidation = validateRegex.test(context);
    const hasGuard = useGuardRegex.test(context);
    const hasUpload = uploadRegex.test(context);

    routes.push({
      httpMethod,
      path: routePath.startsWith('/') ? routePath : '/' + routePath,
      methodName,
      params,
      hasValidation,
      hasGuard,
      hasUpload,
    });
  }

  if (routes.length === 0) return null;
  return { basePath, className, routes, filePath };
}

// ─── Main ───

const tsFiles = findFiles(projectDir, /\.ts$/);
const controllers = tsFiles.map(parseControllerFile).filter(Boolean);

if (controllers.length === 0) {
  console.log('No controllers with route decorators found.');
  process.exit(0);
}

// ─── Generate OpenAPI spec ───

const pkgPath = path.join(projectDir, 'package.json');
const pkg = fs.existsSync(pkgPath) ? JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) : {};

const spec = {
  openapi: '3.1.0',
  info: {
    title: pkg.name || 'Velocity API',
    version: pkg.version || '1.0.0',
    description: pkg.description || 'Auto-generated by velogen-openapi',
  },
  paths: {},
};

for (const ctrl of controllers) {
  for (const route of ctrl.routes) {
    const fullPath = (ctrl.basePath + route.path)
      .replace(/\/+/g, '/')           // collapse double slashes
      .replace(/:(\w+)/g, '{$1}');     // :id → {id}

    if (!spec.paths[fullPath]) spec.paths[fullPath] = {};

    const operation = {
      operationId: `${ctrl.className}_${route.methodName}`,
      tags: [ctrl.className],
      responses: {
        '200': { description: 'Successful response', content: { 'application/json': { schema: { type: 'object' } } } },
        '204': { description: 'No content' },
      },
    };

    // Path parameters
    if (route.params.length > 0) {
      operation.parameters = route.params.map(name => ({
        name,
        in: 'path',
        required: true,
        schema: { type: 'string' },
      }));
    }

    // Request body for POST/PUT/PATCH
    if (['post', 'put', 'patch'].includes(route.httpMethod)) {
      if (route.hasUpload) {
        operation.requestBody = {
          content: { 'multipart/form-data': { schema: { type: 'object' } } },
        };
      } else {
        operation.requestBody = {
          content: { 'application/json': { schema: { type: 'object' } } },
        };
      }
    }

    // Security hint if guarded
    if (route.hasGuard) {
      operation.security = [{ bearerAuth: [] }];
    }

    if (route.hasGuard) {
      operation.responses['403'] = { description: 'Forbidden' };
    }
    if (route.hasValidation) {
      operation.responses['400'] = { description: 'Validation error' };
    }

    spec.paths[fullPath][route.httpMethod] = operation;
  }
}

// Add security scheme if any guarded route exists
const hasAnyGuard = controllers.some(c => c.routes.some(r => r.hasGuard));
if (hasAnyGuard) {
  spec.components = {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
    },
  };
}

const outputDir = path.join(projectDir, 'velo');
fs.mkdirSync(outputDir, { recursive: true });
const outputFile = path.join(outputDir, 'openapi.json');
fs.writeFileSync(outputFile, JSON.stringify(spec, null, 2) + '\n');

const routeCount = controllers.reduce((sum, c) => sum + c.routes.length, 0);
console.log(`velogen-openapi: generated ${path.relative(process.cwd(), outputFile)}`);
console.log(`  ${routeCount} routes across ${controllers.length} controller(s)`);
for (const ctrl of controllers) {
  console.log(`  ${ctrl.className} (${ctrl.basePath}): ${ctrl.routes.map(r => `${r.httpMethod.toUpperCase()} ${r.path}`).join(', ')}`);
}
