#!/usr/bin/env node
/**
 * velogen-client — Velocity Typed Client Generator
 *
 * Scans controller files for @Controller, @Get/@Post/etc. decorators and
 * generates a typed fetch client module. Similar in spirit to Elysia's Eden Treaty
 * but code-generated (like Prisma Client) rather than type-level magic.
 *
 * Usage:
 *   node scripts/velogen-client.js <project-dir> [--base-url=http://localhost:5000]
 *   npm run client -- examples/full-demo
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const targetDir = args.find(a => !a.startsWith('--'));
const baseUrlArg = args.find(a => a.startsWith('--base-url='));
const defaultBaseUrl = baseUrlArg ? baseUrlArg.split('=')[1] : 'http://localhost:5000';

if (!targetDir) {
  console.error('Usage: velogen-client <project-directory> [--base-url=http://localhost:5000]');
  process.exit(1);
}

const projectDir = path.resolve(targetDir);
if (!fs.existsSync(projectDir)) {
  console.error(`Directory not found: ${projectDir}`);
  process.exit(1);
}

// ─── Helpers ───

function findFiles(dir, pattern) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== 'velo' && entry.name !== 'dist') {
      results.push(...findFiles(fullPath, pattern));
    } else if (entry.isFile() && pattern.test(entry.name)) {
      results.push(fullPath);
    }
  }
  return results;
}

// ─── Parse controller files ───

const HTTP_METHODS = ['Get', 'Post', 'Put', 'Delete', 'Patch'];
const methodRegex = new RegExp(
  `@(${HTTP_METHODS.join('|')})\\s*\\(\\s*['"\`]([^'"\`]*)['"\`]\\s*\\)`,
  'g'
);
const controllerRegex = /@Controller\s*\(\s*['"`]([^'"`]*)['"`]\s*\)/;

function parseControllerFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const ctrlMatch = content.match(controllerRegex);
  if (!ctrlMatch) return null;

  const basePath = ctrlMatch[1];
  const className = (content.match(/(?:export\s+)?class\s+(\w+)/) || [])[1] || 'Unknown';
  const routes = [];

  let match;
  methodRegex.lastIndex = 0;
  while ((match = methodRegex.exec(content)) !== null) {
    const httpMethod = match[1].toLowerCase();
    const routePath = match[2];
    const afterDecorator = content.slice(match.index + match[0].length);
    let methodName = 'unknown';
    for (const line of afterDecorator.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('@') || trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
      const m = trimmed.match(/^(?:async\s+)?(\w+)\s*\(/);
      if (m) { methodName = m[1]; break; }
    }

    const params = [];
    const paramMatches = routePath.matchAll(/:(\w+)/g);
    for (const pm of paramMatches) params.push(pm[1]);

    routes.push({ httpMethod, path: routePath.startsWith('/') ? routePath : '/' + routePath, methodName, params });
  }

  if (routes.length === 0) return null;
  return { basePath, className, routes };
}

// ─── Main ───

const tsFiles = findFiles(projectDir, /\.ts$/);
const controllers = tsFiles.map(parseControllerFile).filter(Boolean);

if (controllers.length === 0) {
  console.log('No controllers with route decorators found.');
  process.exit(0);
}

// ─── Generate typed client ───

let output = `// Auto-generated by velogen-client — do not edit manually\n`;
output += `// Re-run: npm run client -- ${path.relative(process.cwd(), projectDir)}\n\n`;
output += `const BASE = '${defaultBaseUrl}';\n\n`;
output += `type RequestOptions = { headers?: Record<string, string>; signal?: AbortSignal };\n\n`;

output += `async function _fetch(method: string, path: string, body?: any, opts?: RequestOptions) {\n`;
output += `  const headers: Record<string, string> = { ...opts?.headers };\n`;
output += `  const init: RequestInit = { method, headers, signal: opts?.signal };\n`;
output += `  if (body !== undefined) {\n`;
output += `    headers['Content-Type'] = 'application/json';\n`;
output += `    init.body = JSON.stringify(body);\n`;
output += `  }\n`;
output += `  const res = await fetch(BASE + path, init);\n`;
output += `  if (res.status === 204) return undefined;\n`;
output += `  const text = await res.text();\n`;
output += `  try { return JSON.parse(text); } catch { return text; }\n`;
output += `}\n\n`;

// Group routes by controller into namespace objects
for (const ctrl of controllers) {
  const nsName = ctrl.className.replace(/Controller$/, '').toLowerCase();
  output += `export const ${nsName} = {\n`;

  for (const route of ctrl.routes) {
    const fullPath = (ctrl.basePath + route.path).replace(/\/+/g, '/');

    // Build parameter list
    const fnParams = [];
    for (const p of route.params) fnParams.push(`${p}: string`);
    const hasBody = ['post', 'put', 'patch'].includes(route.httpMethod);
    if (hasBody) fnParams.push('body: any');
    fnParams.push('opts?: RequestOptions');

    // Build URL with template literals for params
    let urlExpr;
    if (route.params.length > 0) {
      urlExpr = '`' + fullPath.replace(/:(\w+)/g, '${$1}') + '`';
    } else {
      urlExpr = `'${fullPath}'`;
    }

    const bodyArg = hasBody ? ', body' : ', undefined';
    output += `  ${route.methodName}: (${fnParams.join(', ')}) =>\n`;
    output += `    _fetch('${route.httpMethod.toUpperCase()}', ${urlExpr}${bodyArg}, opts),\n`;
  }

  output += `};\n\n`;
}

const outputDir = path.join(projectDir, 'velo');
fs.mkdirSync(outputDir, { recursive: true });
const outputFile = path.join(outputDir, 'velocity-client.ts');
fs.writeFileSync(outputFile, output);

const routeCount = controllers.reduce((sum, c) => sum + c.routes.length, 0);
console.log(`velogen-client: generated ${path.relative(process.cwd(), outputFile)}`);
console.log(`  ${routeCount} routes across ${controllers.length} controller(s)`);
for (const ctrl of controllers) {
  const nsName = ctrl.className.replace(/Controller$/, '').toLowerCase();
  console.log(`  ${nsName}: ${ctrl.routes.map(r => r.methodName).join(', ')}`);
}
