#!/usr/bin/env node
/**
 * velogen-client — Velocity Typed Client Generator
 *
 * Generates a typed client with:
 *   - REST endpoints grouped by controller namespace
 *   - .fn namespace for @Fn HTTP function calls
 *   - .ws namespace for @WebSocket + @Command gateways
 *
 * Usage:
 *   node scripts/velogen-client.js <project-dir> [--base-url=http://localhost:5000]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const targetDir = args.find(a => !a.startsWith('--'));
const baseUrlArg = args.find(a => a.startsWith('--base-url='));
const defaultBaseUrl = baseUrlArg ? baseUrlArg.split('=')[1] : 'http://localhost:5000';

if (!targetDir) {
  console.error('Usage: velogen-client <project-directory> [--base-url=http://localhost:5000]');
  process.exit(1);
}

const projectDir = path.resolve(targetDir);
if (!fs.existsSync(projectDir)) {
  console.error(`Directory not found: ${projectDir}`);
  process.exit(1);
}

// ─── Helpers ───

function findFiles(dir, pattern) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== 'velo' && entry.name !== 'dist') {
      results.push(...findFiles(fullPath, pattern));
    } else if (entry.isFile() && pattern.test(entry.name)) {
      results.push(fullPath);
    }
  }
  return results;
}

function findMethodName(content, startIndex) {
  const after = content.slice(startIndex);
  for (const line of after.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('@') || trimmed.startsWith('//') || trimmed.startsWith('*')) continue;
    const m = trimmed.match(/^(?:async\s+)?(\w+)\s*\(/);
    if (m) return m[1];
  }
  return 'unknown';
}

// ─── Parse controllers ───

const HTTP_METHODS = ['Get', 'Post', 'Put', 'Delete', 'Patch'];
const methodRegex = new RegExp(
  `@(${HTTP_METHODS.join('|')})\\s*\\(\\s*['"\`]([^'"\`]*)['"\`]\\s*\\)`, 'g'
);
const controllerRegex = /@Controller\s*\(\s*['"`]([^'"`]*)['"`]\s*\)/;

function parseControllerFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const ctrlMatch = content.match(controllerRegex);
  if (!ctrlMatch) return null;

  const basePath = ctrlMatch[1];
  const className = (content.match(/(?:export\s+)?class\s+(\w+)/) || [])[1] || 'Unknown';
  const routes = [];

  let match;
  methodRegex.lastIndex = 0;
  while ((match = methodRegex.exec(content)) !== null) {
    const httpMethod = match[1].toLowerCase();
    const routePath = match[2];
    const methodName = findMethodName(content, match.index + match[0].length);
    const params = [];
    for (const pm of routePath.matchAll(/:(\w+)/g)) params.push(pm[1]);
    routes.push({ httpMethod, path: routePath.startsWith('/') ? routePath : '/' + routePath, methodName, params });
  }

  if (routes.length === 0) return null;
  return { basePath, className, routes };
}

// ─── Parse @Fn ───

const fnRegex = /@Fn\s*\([^)]*\)/g;

function parseFnDeclarations(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  if (!/@Fn\s*\(/.test(content)) return [];
  const fns = [];

  let match;
  fnRegex.lastIndex = 0;
  while ((match = fnRegex.exec(content)) !== null) {
    const methodName = findMethodName(content, match.index + match[0].length);
    // Try to extract @Fn('alias') — if present, use alias as the function name
    const aliasMatch = match[0].match(/@Fn\s*\(\s*['"`]([^'"`]+)['"`]\s*\)/);
    const fnName = aliasMatch ? aliasMatch[1] : methodName;
    fns.push({ name: fnName, methodName });
  }

  return fns;
}

// ─── Parse @WebSocket + @Command ───

const wsRegex = /@WebSocket\s*\(\s*['"`]([^'"`]*)['"`]\s*\)/;
const cmdRegex = /@Command\s*\(\s*['"`]([^'"`]*)['"`]\s*\)/g;

function parseWsFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const wsMatch = content.match(wsRegex);
  if (!wsMatch) return null;

  const wsPath = wsMatch[1];
  const className = (content.match(/(?:export\s+)?class\s+(\w+)/) || [])[1] || 'Unknown';
  const commands = [];

  let match;
  cmdRegex.lastIndex = 0;
  while ((match = cmdRegex.exec(content)) !== null) {
    commands.push(match[1]);
  }

  return { wsPath, className, commands };
}

// ─── Main ───

const tsFiles = findFiles(projectDir, /\.ts$/);
const controllers = tsFiles.map(parseControllerFile).filter(Boolean);
const allFns = tsFiles.flatMap(f => parseFnDeclarations(f));
const wsGateways = tsFiles.map(parseWsFile).filter(Boolean);

if (controllers.length === 0 && allFns.length === 0 && wsGateways.length === 0) {
  console.log('No controllers, @Fn, or @WebSocket found.');
  process.exit(0);
}

// ─── Generate ───

let output = `// Auto-generated by velogen-client — do not edit manually\n`;
output += `// Re-run: velogen c ${path.relative(process.cwd(), projectDir)}\n\n`;
output += `const BASE = '${defaultBaseUrl}';\n`;
output += `const WS_BASE = BASE.replace(/^http/, 'ws');\n\n`;
output += `type RequestOptions = { headers?: Record<string, string>; signal?: AbortSignal };\n\n`;

// HTTP fetch helper
output += `async function _fetch(method: string, path: string, body?: unknown, opts?: RequestOptions) {\n`;
output += `  const headers: Record<string, string> = { ...opts?.headers };\n`;
output += `  const init: RequestInit = { method, headers, signal: opts?.signal };\n`;
output += `  if (body !== undefined) {\n`;
output += `    headers['Content-Type'] = 'application/json';\n`;
output += `    init.body = JSON.stringify(body);\n`;
output += `  }\n`;
output += `  const res = await fetch(BASE + path, init);\n`;
output += `  if (res.status === 204) return undefined;\n`;
output += `  const text = await res.text();\n`;
output += `  try { return JSON.parse(text); } catch { return text; }\n`;
output += `}\n\n`;

// REST endpoints by controller
for (const ctrl of controllers) {
  const nsName = ctrl.className.replace(/Controller$/, '').toLowerCase();
  output += `export const ${nsName} = {\n`;

  for (const route of ctrl.routes) {
    const fullPath = (ctrl.basePath + route.path).replace(/\/+/g, '/');
    const fnParams = [];
    for (const p of route.params) fnParams.push(`${p}: string`);
    const hasBody = ['post', 'put', 'patch'].includes(route.httpMethod);
    if (hasBody) fnParams.push('body: unknown');
    fnParams.push('opts?: RequestOptions');

    let urlExpr;
    if (route.params.length > 0) {
      urlExpr = '`' + fullPath.replace(/:(\w+)/g, '${$1}') + '`';
    } else {
      urlExpr = `'${fullPath}'`;
    }

    const bodyArg = hasBody ? ', body' : ', undefined';
    output += `  ${route.methodName}: (${fnParams.join(', ')}) =>\n`;
    output += `    _fetch('${route.httpMethod.toUpperCase()}', ${urlExpr}${bodyArg}, opts),\n`;
  }

  output += `};\n\n`;
}

// @Fn namespace
if (allFns.length > 0) {
  output += `// ─── HTTP Function Calls (@Fn) ───\n\n`;
  output += `export const fn = {\n`;
  for (const f of allFns) {
    output += `  ${f.name}: (...args: unknown[]) =>\n`;
    output += `    _fetch('GET', \`/.\${encodeURIComponent('${f.name}')}(\${args.map(a => typeof a === 'string' ? \`"\${a}"\` : String(a)).join(',')})\`),\n`;
  }
  output += `};\n\n`;
}

// WebSocket namespace
if (wsGateways.length > 0) {
  output += `// ─── WebSocket ───\n\n`;
  output += `interface WsResponse { ok: boolean; cmd: string; data: unknown; error: string | null }\n\n`;

  output += `function _ws(path: string) {\n`;
  output += `  const ws = new globalThis.WebSocket(WS_BASE + path);\n`;
  output += `  const pending = new Map<string, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();\n`;
  output += `  let idCounter = 0;\n`;
  output += `  ws.onmessage = (e) => {\n`;
  output += `    try {\n`;
  output += `      const msg: WsResponse = JSON.parse(e.data);\n`;
  output += `      const p = pending.get(msg.cmd);\n`;
  output += `      if (p) { pending.delete(msg.cmd); msg.ok ? p.resolve(msg.data) : p.reject(new Error(msg.error || 'Unknown error')); }\n`;
  output += `    } catch {}\n`;
  output += `  };\n`;
  output += `  return {\n`;
  output += `    raw: ws,\n`;
  output += `    send(cmd: string, data?: unknown): Promise<unknown> {\n`;
  output += `      return new Promise((resolve, reject) => {\n`;
  output += `        pending.set(cmd, { resolve, reject });\n`;
  output += `        ws.send(JSON.stringify({ cmd, data }));\n`;
  output += `      });\n`;
  output += `    },\n`;
  output += `    close() { ws.close(); },\n`;
  output += `  };\n`;
  output += `}\n\n`;

  output += `export const ws = {\n`;
  for (const gw of wsGateways) {
    const nsName = gw.className.replace(/Gateway$/, '').toLowerCase();
    output += `  ${nsName}: {\n`;
    output += `    connect: () => {\n`;
    output += `      const conn = _ws('${gw.wsPath}');\n`;
    output += `      return {\n`;
    output += `        ...conn,\n`;
    if (gw.commands.length > 0) {
      for (const cmd of gw.commands) {
        output += `        ${cmd}: (data?: unknown) => conn.send('${cmd}', data),\n`;
      }
    }
    output += `      };\n`;
    output += `    },\n`;
    output += `  },\n`;
  }
  output += `};\n`;
}

const outputDir = path.join(projectDir, 'velo');
fs.mkdirSync(outputDir, { recursive: true });
const outputFile = path.join(outputDir, 'velocity-client.ts');
fs.writeFileSync(outputFile, output);

const routeCount = controllers.reduce((sum, c) => sum + c.routes.length, 0);
console.log(`velogen-client: generated ${path.relative(process.cwd(), outputFile)}`);
console.log(`  ${routeCount} REST routes, ${allFns.length} @Fn functions, ${wsGateways.length} WebSocket gateways`);
for (const ctrl of controllers) {
  const nsName = ctrl.className.replace(/Controller$/, '').toLowerCase();
  console.log(`  ${nsName}: ${ctrl.routes.map(r => r.methodName).join(', ')}`);
}
if (allFns.length > 0) console.log(`  fn: ${allFns.map(f => f.name).join(', ')}`);
for (const gw of wsGateways) {
  const nsName = gw.className.replace(/Gateway$/, '').toLowerCase();
  console.log(`  ws.${nsName}: ${gw.commands.length > 0 ? gw.commands.join(', ') : '(manual onMessage)'}`);
}
